// All datasets from the CEO demo, stored as JSON so the UI can read everything from here.
// 7 core tables are exposed under DB, and the dashboard summary lives under ALKHEBRA_DATA.

window.DB = {
  dataset_1_instructor_master: [
    { emp_id: 'INS001', name: 'Ahmed Al-Mansoori', nationality: 'Qatari', gender: 'M', age: 42, hire_date: '2022-01-15', exit_date: null, status: 'Active', monthly_salary_qar: 12500, recruitment_cost_qar: 2000, licensing_cost_qar: 0, department: 'General Training', manager_id: 'MGR001' },
    { emp_id: 'INS002', name: 'Fatima Al-Hajri', nationality: 'Qatari', gender: 'F', age: 35, hire_date: '2022-03-10', exit_date: null, status: 'Active', monthly_salary_qar: 12500, recruitment_cost_qar: 2000, licensing_cost_qar: 0, department: "Women's Section", manager_id: 'MGR002' },
    { emp_id: 'INS003', name: 'Mohammed Iqbal', nationality: 'Pakistani', gender: 'M', age: 38, hire_date: '2023-02-01', exit_date: null, status: 'Active', monthly_salary_qar: 7500, recruitment_cost_qar: 8000, licensing_cost_qar: 50000, department: 'General Training', manager_id: 'MGR001' },
    { emp_id: 'INS004', name: 'Samir Khalil', nationality: 'Egyptian', gender: 'M', age: 45, hire_date: '2023-02-15', exit_date: '2024-01-15', status: 'Terminated', monthly_salary_qar: 7000, recruitment_cost_qar: 7500, licensing_cost_qar: 50000, department: 'General Training', manager_id: 'MGR001' },
    { emp_id: 'INS005', name: 'Yusuf Abdi', nationality: 'Kenyan', gender: 'M', age: 32, hire_date: '2023-03-01', exit_date: null, status: 'Active', monthly_salary_qar: 7200, recruitment_cost_qar: 9000, licensing_cost_qar: 50000, department: 'General Training', manager_id: 'MGR001' },
    { emp_id: 'INS006', name: 'Hassan Razak', nationality: 'Sri Lankan', gender: 'M', age: 41, hire_date: '2023-03-15', exit_date: '2024-02-28', status: 'Terminated', monthly_salary_qar: 6800, recruitment_cost_qar: 7000, licensing_cost_qar: 50000, department: 'General Training', manager_id: 'MGR001' },
    { emp_id: 'INS007', name: 'Aisha Syed', nationality: 'Indian', gender: 'F', age: 29, hire_date: '2023-04-01', exit_date: null, status: 'Active', monthly_salary_qar: 7500, recruitment_cost_qar: 8500, licensing_cost_qar: 50000, department: "Women's Section", manager_id: 'MGR002' },
    { emp_id: 'INS008', name: 'Karim Mostafa', nationality: 'Jordanian', gender: 'M', age: 36, hire_date: '2023-05-15', exit_date: null, status: 'Active', monthly_salary_qar: 7800, recruitment_cost_qar: 6500, licensing_cost_qar: 50000, department: 'General Training', manager_id: 'MGR001' },
    { emp_id: 'INS009', name: 'Layla Hassan', nationality: 'Lebanese', gender: 'F', age: 33, hire_date: '2023-06-01', exit_date: null, status: 'Active', monthly_salary_qar: 8000, recruitment_cost_qar: 6000, licensing_cost_qar: 50000, department: "Women's Section", manager_id: 'MGR002' },
    { emp_id: 'INS010', name: 'David Omondi', nationality: 'Kenyan', gender: 'M', age: 39, hire_date: '2023-07-01', exit_date: '2024-03-30', status: 'Terminated', monthly_salary_qar: 7200, recruitment_cost_qar: 9000, licensing_cost_qar: 50000, department: 'General Training', manager_id: 'MGR001' },
    { emp_id: 'INS011', name: 'Rashid Al-Kuwari', nationality: 'Qatari', gender: 'M', age: 51, hire_date: '2022-11-01', exit_date: null, status: 'Active', monthly_salary_qar: 13000, recruitment_cost_qar: 2000, licensing_cost_qar: 0, department: 'Autonomous Vehicle', manager_id: 'MGR003' },
    { emp_id: 'INS012', name: 'Nadia Cherif', nationality: 'Tunisian', gender: 'F', age: 37, hire_date: '2023-08-15', exit_date: null, status: 'Active', monthly_salary_qar: 7600, recruitment_cost_qar: 7000, licensing_cost_qar: 50000, department: "Women's Section", manager_id: 'MGR002' },
    { emp_id: 'INS013', name: 'Tariq Mahmood', nationality: 'Pakistani', gender: 'M', age: 44, hire_date: '2023-09-01', exit_date: null, status: 'Active', monthly_salary_qar: 7500, recruitment_cost_qar: 8000, licensing_cost_qar: 50000, department: 'General Training', manager_id: 'MGR001' },
    { emp_id: 'INS014', name: 'Priya Krishnamurthy', nationality: 'Indian', gender: 'F', age: 31, hire_date: '2023-10-01', exit_date: '2024-04-15', status: 'Terminated', monthly_salary_qar: 7400, recruitment_cost_qar: 8500, licensing_cost_qar: 50000, department: "Women's Section", manager_id: 'MGR002' },
    { emp_id: 'INS015', name: 'Abdullah Al-Marri', nationality: 'Qatari', gender: 'M', age: 47, hire_date: '2022-08-01', exit_date: null, status: 'Active', monthly_salary_qar: 13500, recruitment_cost_qar: 2000, licensing_cost_qar: 0, department: 'General Training', manager_id: 'MGR001' }
  ],

  dataset_2_lesson_performance: [
    { lesson_id: 'L001',  date: '2024-01-15', emp_id: 'INS003', student_id: 'STU045', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Indian',      student_gender: 'M', notes: 'Good instructor, very patient' },
    { lesson_id: 'L002',  date: '2024-01-15', emp_id: 'INS003', student_id: 'STU046', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Excellent, explained everything clearly' },
    { lesson_id: 'L003',  date: '2024-01-16', emp_id: 'INS003', student_id: 'STU047', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Bangladeshi', student_gender: 'M', notes: 'Very happy with lessons' },
    { lesson_id: 'L004',  date: '2024-01-16', emp_id: 'INS003', student_id: 'STU048', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Indian',      student_gender: 'M', notes: "Best instructor I've had" },
    { lesson_id: 'L005',  date: '2024-01-17', emp_id: 'INS003', student_id: 'STU049', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Made me feel confident' },
    { lesson_id: 'L006',  date: '2024-01-17', emp_id: 'INS003', student_id: 'STU050', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Sri Lankan', student_gender: 'M', notes: 'Very professional' },
    { lesson_id: 'L007',  date: '2024-01-18', emp_id: 'INS003', student_id: 'STU051', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Indian',      student_gender: 'M', notes: 'Good experience' },
    { lesson_id: 'L008',  date: '2024-01-18', emp_id: 'INS003', student_id: 'STU052', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Highly recommend' },
    { lesson_id: 'L009',  date: '2024-01-19', emp_id: 'INS003', student_id: 'STU053', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Bangladeshi', student_gender: 'M', notes: 'Great teacher' },
    { lesson_id: 'L010',  date: '2024-01-19', emp_id: 'INS003', student_id: 'STU054', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Indian',      student_gender: 'M', notes: 'Satisfied with training' },
    { lesson_id: 'L011',  date: '2024-01-20', emp_id: 'INS003', student_id: 'STU101', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Very clear instructions' },
    { lesson_id: 'L012',  date: '2024-01-20', emp_id: 'INS003', student_id: 'STU102', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Indian',      student_gender: 'M', notes: 'Patient and knowledgeable' },
    { lesson_id: 'L013',  date: '2024-01-21', emp_id: 'INS003', student_id: 'STU103', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Bangladeshi', student_gender: 'M', notes: 'Good experience overall' },
    { lesson_id: 'L014',  date: '2024-01-21', emp_id: 'INS003', student_id: 'STU104', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Sri Lankan', student_gender: 'M', notes: 'Explained everything well' },
    { lesson_id: 'L015',  date: '2024-01-22', emp_id: 'INS003', student_id: 'STU105', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Very professional' },
    { lesson_id: 'L016',  date: '2024-02-01', emp_id: 'INS005', student_id: 'STU055', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Kenyan',      student_gender: 'M', notes: 'Very helpful, patient' },
    { lesson_id: 'L017',  date: '2024-02-01', emp_id: 'INS005', student_id: 'STU056', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Ugandan',     student_gender: 'M', notes: 'Good instructor' },
    { lesson_id: 'L018',  date: '2024-02-02', emp_id: 'INS005', student_id: 'STU057', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 3, student_nationality: 'Nigerian',    student_gender: 'M', notes: 'Rushed through some parts' },
    { lesson_id: 'L019',  date: '2024-02-02', emp_id: 'INS005', student_id: 'STU058', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Ghanaian',    student_gender: 'M', notes: 'Excellent, very clear' },
    { lesson_id: 'L020',  date: '2024-02-03', emp_id: 'INS005', student_id: 'STU059', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Kenyan',      student_gender: 'M', notes: 'Good experience' },
    { lesson_id: 'L021',  date: '2024-02-03', emp_id: 'INS005', student_id: 'STU106', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Tanzanian',   student_gender: 'M', notes: 'Very thorough training' },
    { lesson_id: 'L022',  date: '2024-02-04', emp_id: 'INS005', student_id: 'STU107', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Ugandan',     student_gender: 'M', notes: 'Solid instruction' },
    { lesson_id: 'L023',  date: '2024-02-04', emp_id: 'INS005', student_id: 'STU108', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Kenyan',      student_gender: 'M', notes: 'Patient teacher' },
    { lesson_id: 'L024',  date: '2024-02-05', emp_id: 'INS005', student_id: 'STU109', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Nigerian',    student_gender: 'M', notes: 'Good, but sometimes fast' },
    { lesson_id: 'L025',  date: '2024-02-05', emp_id: 'INS005', student_id: 'STU110', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Ghanaian',    student_gender: 'M', notes: 'Excellent preparation' },
    { lesson_id: 'L026',  date: '2024-02-06', emp_id: 'INS005', student_id: 'STU111', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Kenyan',      student_gender: 'M', notes: 'Very supportive' },
    { lesson_id: 'L027',  date: '2024-02-06', emp_id: 'INS005', student_id: 'STU112', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Ugandan',     student_gender: 'M', notes: 'Good lessons' },
    { lesson_id: 'L028',  date: '2024-02-15', emp_id: 'INS010', student_id: 'STU060', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 2, student_nationality: 'Indian',      student_gender: 'F', notes: 'Made inappropriate comments, felt uncomfortable' },
    { lesson_id: 'L029',  date: '2024-02-15', emp_id: 'INS010', student_id: 'STU061', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 1, student_nationality: 'Pakistani',   student_gender: 'F', notes: 'Asked for my phone number, very unprofessional' },
    { lesson_id: 'L030',  date: '2024-02-16', emp_id: 'INS010', student_id: 'STU062', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 2, student_nationality: 'Sri Lankan', student_gender: 'F', notes: 'Language was rude, used foul words' },
    { lesson_id: 'L031',  date: '2024-02-16', emp_id: 'INS010', student_id: 'STU063', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 3, student_nationality: 'Indian',      student_gender: 'M', notes: 'Okay, but seems distracted' },
    { lesson_id: 'L032',  date: '2024-02-17', emp_id: 'INS010', student_id: 'STU064', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 1, student_nationality: 'Bangladeshi', student_gender: 'F', notes: 'Made me very uncomfortable, requested female instructor' },
    { lesson_id: 'L033',  date: '2024-02-17', emp_id: 'INS010', student_id: 'STU113', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 1, student_nationality: 'Indian',      student_gender: 'F', notes: 'Kept asking personal questions' },
    { lesson_id: 'L034',  date: '2024-02-18', emp_id: 'INS010', student_id: 'STU114', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 2, student_nationality: 'Pakistani',   student_gender: 'F', notes: 'Made comments about my appearance' },
    { lesson_id: 'L035',  date: '2024-02-18', emp_id: 'INS010', student_id: 'STU115', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 3, student_nationality: 'Indian',      student_gender: 'M', notes: 'Okay instructor' },
    { lesson_id: 'L036',  date: '2024-02-19', emp_id: 'INS010', student_id: 'STU116', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 1, student_nationality: 'Sri Lankan', student_gender: 'F', notes: 'Very uncomfortable experience' },
    { lesson_id: 'L037',  date: '2024-02-19', emp_id: 'INS010', student_id: 'STU117', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 2, student_nationality: 'Indian',      student_gender: 'M', notes: 'Seemed distracted during lesson' },
    { lesson_id: 'L038',  date: '2024-02-20', emp_id: 'INS010', student_id: 'STU118', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 1, student_nationality: 'Bangladeshi', student_gender: 'F', notes: 'Made inappropriate jokes' },
    { lesson_id: 'L039',  date: '2024-03-01', emp_id: 'INS004', student_id: 'STU065', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 3, student_nationality: 'Indian',      student_gender: 'M', notes: 'Decent instructor' },
    { lesson_id: 'L040',  date: '2024-03-01', emp_id: 'INS004', student_id: 'STU066', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 2, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Asked for bribe to pass test' },
    { lesson_id: 'L041',  date: '2024-03-02', emp_id: 'INS004', student_id: 'STU067', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 2, student_nationality: 'Egyptian',    student_gender: 'M', notes: 'Suggested paying extra for guaranteed pass' },
    { lesson_id: 'L042',  date: '2024-03-02', emp_id: 'INS004', student_id: 'STU068', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 1, student_nationality: 'Jordanian',   student_gender: 'M', notes: 'Openly asked for money to pass' },
    { lesson_id: 'L043',  date: '2024-03-03', emp_id: 'INS004', student_id: 'STU069', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 2, student_nationality: 'Syrian',      student_gender: 'M', notes: 'Corrupt, wanted bribe' },
    { lesson_id: 'L044',  date: '2024-03-03', emp_id: 'INS004', student_id: 'STU119', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 2, student_nationality: 'Indian',      student_gender: 'M', notes: 'Hinted at needing extra fees' },
    { lesson_id: 'L045',  date: '2024-03-04', emp_id: 'INS004', student_id: 'STU120', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 3, student_nationality: 'Egyptian',    student_gender: 'M', notes: 'Made me uncomfortable with money talk' },
    { lesson_id: 'L046',  date: '2024-03-04', emp_id: 'INS004', student_id: 'STU121', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 1, student_nationality: 'Jordanian',   student_gender: 'M', notes: 'Demanded payment to pass' },
    { lesson_id: 'L047',  date: '2024-03-05', emp_id: 'INS004', student_id: 'STU122', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 2, student_nationality: 'Syrian',      student_gender: 'M', notes: 'Corrupt behavior, very disappointing' },
    { lesson_id: 'L048',  date: '2024-01-10', emp_id: 'INS011', student_id: 'STU070', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Amazing technology, felt safe' },
    { lesson_id: 'L049',  date: '2024-01-10', emp_id: 'INS011', student_id: 'STU071', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'The car teaches you perfectly' },
    { lesson_id: 'L050',  date: '2024-01-11', emp_id: 'INS011', student_id: 'STU072', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Incredible experience, learned fast' },
    { lesson_id: 'L051',  date: '2024-01-11', emp_id: 'INS011', student_id: 'STU073', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Emirati',     student_gender: 'F', notes: 'Wish all lessons were like this' },
    { lesson_id: 'L052',  date: '2024-01-12', emp_id: 'INS011', student_id: 'STU074', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'The sensors catch every mistake' },
    { lesson_id: 'L053',  date: '2024-01-12', emp_id: 'INS011', student_id: 'STU123', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'So much less stressful than regular car' },
    { lesson_id: 'L054',  date: '2024-01-13', emp_id: 'INS011', student_id: 'STU124', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Saudi',       student_gender: 'F', notes: 'Perfect for nervous drivers' },
    { lesson_id: 'L055',  date: '2024-01-13', emp_id: 'INS011', student_id: 'STU125', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Technology is amazing' },
    { lesson_id: 'L056',  date: '2024-01-14', emp_id: 'INS011', student_id: 'STU126', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Emirati',     student_gender: 'F', notes: 'Learned so quickly' },
    { lesson_id: 'L057',  date: '2024-01-14', emp_id: 'INS011', student_id: 'STU127', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'The feedback is instant and helpful' },
    { lesson_id: 'L058',  date: '2024-01-15', emp_id: 'INS011', student_id: 'STU128', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Kuwaiti',     student_gender: 'M', notes: 'Best decision to use this car' },
    { lesson_id: 'L059',  date: '2024-01-15', emp_id: 'INS011', student_id: 'STU129', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Felt completely safe the whole time' },
    { lesson_id: 'L060',  date: '2024-01-16', emp_id: 'INS011', student_id: 'STU130', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Passed first time thanks to this' },
    { lesson_id: 'L061',  date: '2024-01-12', emp_id: 'INS012', student_id: 'STU075', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Excellent female instructor, very respectful' },
    { lesson_id: 'L062',  date: '2024-01-13', emp_id: 'INS012', student_id: 'STU076', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Perfect, understood my needs as a woman' },
    { lesson_id: 'L063',  date: '2024-01-13', emp_id: 'INS012', student_id: 'STU077', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Saudi',       student_gender: 'F', notes: 'Very professional, highly recommend' },
    { lesson_id: 'L064',  date: '2024-01-14', emp_id: 'INS012', student_id: 'STU131', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Made me feel comfortable learning' },
    { lesson_id: 'L065',  date: '2024-01-14', emp_id: 'INS012', student_id: 'STU132', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Patient and understanding' },
    { lesson_id: 'L066',  date: '2024-01-15', emp_id: 'INS012', student_id: 'STU133', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Kuwaiti',     student_gender: 'F', notes: 'Best female instructor' },
    { lesson_id: 'L067',  date: '2024-01-15', emp_id: 'INS012', student_id: 'STU134', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Very professional and kind' },
    { lesson_id: 'L068',  date: '2024-01-16', emp_id: 'INS012', student_id: 'STU135', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Good instructor, very respectful' },
    { lesson_id: 'L069',  date: '2024-02-20', emp_id: 'INS007', student_id: 'STU078', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Kind, patient, wonderful teacher' },
    { lesson_id: 'L070',  date: '2024-02-20', emp_id: 'INS007', student_id: 'STU079', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Made me feel comfortable learning' },
    { lesson_id: 'L071',  date: '2024-02-21', emp_id: 'INS007', student_id: 'STU136', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Excellent with nervous students' },
    { lesson_id: 'L072',  date: '2024-02-21', emp_id: 'INS007', student_id: 'STU137', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Saudi',       student_gender: 'F', notes: 'Very understanding and professional' },
    { lesson_id: 'L073',  date: '2024-02-22', emp_id: 'INS007', student_id: 'STU138', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Perfect instructor for women' },
    { lesson_id: 'L074',  date: '2024-02-22', emp_id: 'INS007', student_id: 'STU139', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'So patient and encouraging' },
    { lesson_id: 'L075',  date: '2024-03-15', emp_id: 'INS006', student_id: 'STU080', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Indian',      student_gender: 'M', notes: 'Good instructor' },
    { lesson_id: 'L076',  date: '2024-03-15', emp_id: 'INS006', student_id: 'STU081', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Satisfied' },
    { lesson_id: 'L077',  date: '2024-03-16', emp_id: 'INS006', student_id: 'STU082', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 3, student_nationality: 'Bangladeshi', student_gender: 'M', notes: 'Okay, nothing special' },
    { lesson_id: 'L078',  date: '2024-03-16', emp_id: 'INS006', student_id: 'STU083', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Indian',      student_gender: 'M', notes: 'Decent' },
    { lesson_id: 'L079',  date: '2024-03-17', emp_id: 'INS006', student_id: 'STU140', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Sri Lankan', student_gender: 'M', notes: 'Good lessons' },
    { lesson_id: 'L080',  date: '2024-03-17', emp_id: 'INS006', student_id: 'STU141', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 3, student_nationality: 'Indian',      student_gender: 'M', notes: 'Average experience' },
    { lesson_id: 'L081',  date: '2024-03-18', emp_id: 'INS006', student_id: 'STU142', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Solid instructor' },
    { lesson_id: 'L082',  date: '2024-01-05', emp_id: 'INS001', student_id: 'STU143', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Excellent senior instructor' },
    { lesson_id: 'L083',  date: '2024-01-05', emp_id: 'INS001', student_id: 'STU144', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Very experienced, highly recommend' },
    { lesson_id: 'L084',  date: '2024-01-06', emp_id: 'INS001', student_id: 'STU145', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Masterful teaching' },
    { lesson_id: 'L085',  date: '2024-01-06', emp_id: 'INS002', student_id: 'STU146', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: "Head of women's section is amazing" },
    { lesson_id: 'L086',  date: '2024-01-07', emp_id: 'INS002', student_id: 'STU147', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'So grateful for female instructors' },
    { lesson_id: 'L087',  date: '2024-01-07', emp_id: 'INS002', student_id: 'STU148', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Professional and respectful' },
    { lesson_id: 'L088',  date: '2024-01-08', emp_id: 'INS008', student_id: 'STU149', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Jordanian',   student_gender: 'M', notes: 'Good instructor' },
    { lesson_id: 'L089',  date: '2024-01-08', emp_id: 'INS008', student_id: 'STU150', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Jordanian',   student_gender: 'M', notes: 'Solid training' },
    { lesson_id: 'L090',  date: '2024-01-09', emp_id: 'INS008', student_id: 'STU151', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Egyptian',    student_gender: 'M', notes: 'Very thorough' },
    { lesson_id: 'L091',  date: '2024-01-09', emp_id: 'INS009', student_id: 'STU152', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Lebanese',    student_gender: 'F', notes: 'Excellent female instructor' },
    { lesson_id: 'L092',  date: '2024-01-10', emp_id: 'INS009', student_id: 'STU153', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Lebanese',    student_gender: 'F', notes: 'Very professional' },
    { lesson_id: 'L093',  date: '2024-02-10', emp_id: 'INS013', student_id: 'STU154', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Good instructor' },
    { lesson_id: 'L094',  date: '2024-02-10', emp_id: 'INS013', student_id: 'STU155', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Decent training' },
    { lesson_id: 'L095',  date: '2024-02-11', emp_id: 'INS013', student_id: 'STU156', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 3, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Okay, nothing special' },
    { lesson_id: 'L096',  date: '2024-02-11', emp_id: 'INS015', student_id: 'STU157', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Senior instructor, excellent' },
    { lesson_id: 'L097',  date: '2024-02-12', emp_id: 'INS015', student_id: 'STU158', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Very experienced' },
    { lesson_id: 'L098',  date: '2024-02-12', emp_id: 'INS016', student_id: 'STU159', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Egyptian',    student_gender: 'M', notes: 'Good teacher' },
    { lesson_id: 'L099',  date: '2024-02-13', emp_id: 'INS016', student_id: 'STU160', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Egyptian',    student_gender: 'M', notes: 'Solid instruction' },
    { lesson_id: 'L100',  date: '2024-02-13', emp_id: 'INS017', student_id: 'STU161', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Senior female instructor, excellent' },
    { lesson_id: 'L101',  date: '2024-02-14', emp_id: 'INS017', student_id: 'STU162', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Very professional' },
    { lesson_id: 'L102',  date: '2024-02-14', emp_id: 'INS019', student_id: 'STU163', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Algerian',    student_gender: 'F', notes: 'Great female instructor' },
    { lesson_id: 'L103',  date: '2024-02-15', emp_id: 'INS019', student_id: 'STU164', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Algerian',    student_gender: 'F', notes: 'Very patient' },
    { lesson_id: 'L104',  date: '2024-03-01', emp_id: 'INS020', student_id: 'STU165', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Sri Lankan', student_gender: 'M', notes: 'Good instructor' },
    { lesson_id: 'L105',  date: '2024-03-01', emp_id: 'INS020', student_id: 'STU166', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Sri Lankan', student_gender: 'M', notes: 'Solid training' },
    { lesson_id: 'L106',  date: '2024-03-02', emp_id: 'INS021', student_id: 'STU167', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Excellent female instructor' },
    { lesson_id: 'L107',  date: '2024-03-02', emp_id: 'INS021', student_id: 'STU168', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Very respectful' },
    { lesson_id: 'L108',  date: '2024-03-03', emp_id: 'INS022', student_id: 'STU169', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Good instructor' },
    { lesson_id: 'L109',  date: '2024-03-03', emp_id: 'INS022', student_id: 'STU170', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Decent training' },
    { lesson_id: 'L110',  date: '2024-03-04', emp_id: 'INS024', student_id: 'STU171', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Somali',      student_gender: 'F', notes: 'Excellent female instructor' },
    { lesson_id: 'L111',  date: '2024-03-04', emp_id: 'INS024', student_id: 'STU172', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Somali',      student_gender: 'F', notes: 'Very understanding' },
    { lesson_id: 'L112',  date: '2024-03-05', emp_id: 'INS025', student_id: 'STU173', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Good instructor' },
    { lesson_id: 'L113',  date: '2024-03-05', emp_id: 'INS025', student_id: 'STU174', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Solid' },
    { lesson_id: 'L114',  date: '2024-03-06', emp_id: 'INS026', student_id: 'STU175', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Manager level instruction' },
    { lesson_id: 'L115',  date: '2024-03-06', emp_id: 'INS026', student_id: 'STU176', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Excellent' },
    { lesson_id: 'L116',  date: '2024-03-07', emp_id: 'INS027', student_id: 'STU177', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Sudanese',    student_gender: 'M', notes: 'Good instructor' },
    { lesson_id: 'L117',  date: '2024-03-07', emp_id: 'INS027', student_id: 'STU178', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 3, student_nationality: 'Sudanese',    student_gender: 'M', notes: 'Average' },
    { lesson_id: 'L118',  date: '2024-03-08', emp_id: 'INS029', student_id: 'STU179', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Facility manager covers lessons' },
    { lesson_id: 'L119',  date: '2024-03-08', emp_id: 'INS029', student_id: 'STU180', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Good' },
    { lesson_id: 'L120',  date: '2024-03-09', emp_id: 'INS030', student_id: 'STU181', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Bahraini',    student_gender: 'F', notes: 'Excellent female instructor' },
    { lesson_id: 'L121',  date: '2024-03-09', emp_id: 'INS030', student_id: 'STU182', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Bahraini',    student_gender: 'F', notes: 'Very professional' },
    { lesson_id: 'L122',  date: '2024-01-20', emp_id: 'INS003', student_id: 'STU183', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Indian',      student_gender: 'M', notes: 'Another satisfied student' },
    { lesson_id: 'L123',  date: '2024-01-21', emp_id: 'INS003', student_id: 'STU184', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Perfect instructor' },
    { lesson_id: 'L124',  date: '2024-01-22', emp_id: 'INS003', student_id: 'STU185', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Bangladeshi', student_gender: 'M', notes: 'Highly recommend' },
    { lesson_id: 'L125',  date: '2024-01-23', emp_id: 'INS003', student_id: 'STU186', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Indian',      student_gender: 'M', notes: 'Very good' },
    { lesson_id: 'L126',  date: '2024-01-24', emp_id: 'INS003', student_id: 'STU187', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Sri Lankan', student_gender: 'M', notes: 'Excellent' },
    { lesson_id: 'L127',  date: '2024-02-07', emp_id: 'INS005', student_id: 'STU188', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Kenyan',      student_gender: 'M', notes: 'Great teacher' },
    { lesson_id: 'L128',  date: '2024-02-08', emp_id: 'INS005', student_id: 'STU189', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Ugandan',     student_gender: 'M', notes: 'Good experience' },
    { lesson_id: 'L129',  date: '2024-02-09', emp_id: 'INS005', student_id: 'STU190', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Tanzanian',   student_gender: 'M', notes: 'Very helpful' },
    { lesson_id: 'L130',  date: '2024-02-10', emp_id: 'INS005', student_id: 'STU191', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 3, student_nationality: 'Nigerian',    student_gender: 'M', notes: 'Rushed through parking' },
    { lesson_id: 'L131',  date: '2024-02-11', emp_id: 'INS005', student_id: 'STU192', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Ghanaian',    student_gender: 'M', notes: 'Excellent instructor' },
    { lesson_id: 'L132',  date: '2024-02-21', emp_id: 'INS010', student_id: 'STU193', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 1, student_nationality: 'Indian',      student_gender: 'F', notes: 'Made inappropriate remarks' },
    { lesson_id: 'L133',  date: '2024-02-22', emp_id: 'INS010', student_id: 'STU194', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 2, student_nationality: 'Pakistani',   student_gender: 'F', notes: 'Asked personal questions' },
    { lesson_id: 'L134',  date: '2024-02-23', emp_id: 'INS010', student_id: 'STU195', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 2, student_nationality: 'Indian',      student_gender: 'M', notes: 'Distracted during lesson' },
    { lesson_id: 'L135',  date: '2024-02-24', emp_id: 'INS010', student_id: 'STU196', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 1, student_nationality: 'Bangladeshi', student_gender: 'F', notes: 'Very uncomfortable, would not recommend' },
    { lesson_id: 'L136',  date: '2024-02-25', emp_id: 'INS010', student_id: 'STU197', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 1, student_nationality: 'Sri Lankan', student_gender: 'F', notes: 'Harassment, reported to academy' },
    { lesson_id: 'L137',  date: '2024-03-06', emp_id: 'INS004', student_id: 'STU198', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 2, student_nationality: 'Indian',      student_gender: 'M', notes: 'Wanted extra money' },
    { lesson_id: 'L138',  date: '2024-03-07', emp_id: 'INS004', student_id: 'STU199', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 1, student_nationality: 'Egyptian',    student_gender: 'M', notes: 'Demanded bribe' },
    { lesson_id: 'L139',  date: '2024-03-08', emp_id: 'INS004', student_id: 'STU200', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 2, student_nationality: 'Jordanian',   student_gender: 'M', notes: 'Corrupt behavior' },
    { lesson_id: 'L140',  date: '2024-03-09', emp_id: 'INS004', student_id: 'STU201', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 1, student_nationality: 'Syrian',      student_gender: 'M', notes: 'Money before pass' },
    { lesson_id: 'L141',  date: '2024-01-16', emp_id: 'INS011', student_id: 'STU202', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Incredible car' },
    { lesson_id: 'L142',  date: '2024-01-17', emp_id: 'INS011', student_id: 'STU203', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Technology is the future' },
    { lesson_id: 'L143',  date: '2024-01-18', emp_id: 'INS011', student_id: 'STU204', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Emirati',     student_gender: 'F', notes: 'So safe and easy' },
    { lesson_id: 'L144',  date: '2024-01-19', emp_id: 'INS011', student_id: 'STU205', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Saudi',       student_gender: 'F', notes: 'Wish I used this from day one' },
    { lesson_id: 'L145',  date: '2024-01-20', emp_id: 'INS011', student_id: 'STU206', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Learned twice as fast' },
    { lesson_id: 'L146',  date: '2024-01-16', emp_id: 'INS012', student_id: 'STU207', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Wonderful instructor' },
    { lesson_id: 'L147',  date: '2024-01-17', emp_id: 'INS012', student_id: 'STU208', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Kuwaiti',     student_gender: 'F', notes: 'Very professional' },
    { lesson_id: 'L148',  date: '2024-01-18', emp_id: 'INS012', student_id: 'STU209', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Perfect for women' },
    { lesson_id: 'L149',  date: '2024-02-23', emp_id: 'INS007', student_id: 'STU210', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Excellent teacher' },
    { lesson_id: 'L150',  date: '2024-02-24', emp_id: 'INS007', student_id: 'STU211', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Saudi',       student_gender: 'F', notes: 'Very patient' },
    { lesson_id: 'L151',  date: '2024-02-25', emp_id: 'INS007', student_id: 'STU212', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Highly recommend' },
    { lesson_id: 'L152',  date: '2024-03-19', emp_id: 'INS006', student_id: 'STU213', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Indian',      student_gender: 'M', notes: 'Good' },
    { lesson_id: 'L153',  date: '2024-03-20', emp_id: 'INS006', student_id: 'STU214', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 3, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Okay' },
    { lesson_id: 'L154',  date: '2024-03-21', emp_id: 'INS006', student_id: 'STU215', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Bangladeshi', student_gender: 'M', notes: 'Decent' },
    { lesson_id: 'L155',  date: '2024-03-22', emp_id: 'INS006', student_id: 'STU216', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Sri Lankan', student_gender: 'M', notes: 'Satisfied' },
    { lesson_id: 'L156',  date: '2024-01-25', emp_id: 'INS008', student_id: 'STU217', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Jordanian',   student_gender: 'M', notes: 'Good instructor' },
    { lesson_id: 'L157',  date: '2024-01-26', emp_id: 'INS008', student_id: 'STU218', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Egyptian',    student_gender: 'M', notes: 'Very thorough' },
    { lesson_id: 'L158',  date: '2024-01-27', emp_id: 'INS009', student_id: 'STU219', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Lebanese',    student_gender: 'F', notes: 'Excellent' },
    { lesson_id: 'L159',  date: '2024-01-28', emp_id: 'INS009', student_id: 'STU220', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Lebanese',    student_gender: 'F', notes: 'Very professional' },
    { lesson_id: 'L160',  date: '2024-02-15', emp_id: 'INS013', student_id: 'STU221', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Good' },
    { lesson_id: 'L161',  date: '2024-02-16', emp_id: 'INS013', student_id: 'STU222', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Solid' },
    { lesson_id: 'L162',  date: '2024-02-17', emp_id: 'INS015', student_id: 'STU223', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Senior instructor excellence' },
    { lesson_id: 'L163',  date: '2024-02-18', emp_id: 'INS015', student_id: 'STU224', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Very experienced' },
    { lesson_id: 'L164',  date: '2024-02-19', emp_id: 'INS016', student_id: 'STU225', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Egyptian',    student_gender: 'M', notes: 'Good teacher' },
    { lesson_id: 'L165',  date: '2024-02-20', emp_id: 'INS016', student_id: 'STU226', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Egyptian',    student_gender: 'M', notes: 'Decent' },
    { lesson_id: 'L166',  date: '2024-03-10', emp_id: 'INS019', student_id: 'STU227', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Algerian',    student_gender: 'F', notes: 'Excellent female instructor' },
    { lesson_id: 'L167',  date: '2024-03-11', emp_id: 'INS019', student_id: 'STU228', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Algerian',    student_gender: 'F', notes: 'Very kind' },
    { lesson_id: 'L168',  date: '2024-03-12', emp_id: 'INS020', student_id: 'STU229', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Sri Lankan', student_gender: 'M', notes: 'Good' },
    { lesson_id: 'L169',  date: '2024-03-13', emp_id: 'INS020', student_id: 'STU230', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Sri Lankan', student_gender: 'M', notes: 'Solid' },
    { lesson_id: 'L170',  date: '2024-03-14', emp_id: 'INS021', student_id: 'STU231', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Excellent' },
    { lesson_id: 'L171',  date: '2024-03-15', emp_id: 'INS021', student_id: 'STU232', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Very respectful' },
    { lesson_id: 'L172',  date: '2024-03-16', emp_id: 'INS022', student_id: 'STU233', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Good' },
    { lesson_id: 'L173',  date: '2024-03-17', emp_id: 'INS022', student_id: 'STU234', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Very good' },
    { lesson_id: 'L174',  date: '2024-03-18', emp_id: 'INS024', student_id: 'STU235', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Somali',      student_gender: 'F', notes: 'Excellent female instructor' },
    { lesson_id: 'L175',  date: '2024-03-19', emp_id: 'INS024', student_id: 'STU236', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Somali',      student_gender: 'F', notes: 'Very patient' },
    { lesson_id: 'L176',  date: '2024-03-20', emp_id: 'INS025', student_id: 'STU237', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Good' },
    { lesson_id: 'L177',  date: '2024-03-21', emp_id: 'INS025', student_id: 'STU238', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Solid' },
    { lesson_id: 'L178',  date: '2024-03-22', emp_id: 'INS026', student_id: 'STU239', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Manager level, excellent' },
    { lesson_id: 'L179',  date: '2024-03-23', emp_id: 'INS026', student_id: 'STU240', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Very professional' },
    { lesson_id: 'L180',  date: '2024-03-24', emp_id: 'INS027', student_id: 'STU241', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Sudanese',    student_gender: 'M', notes: 'Good' },
    { lesson_id: 'L181',  date: '2024-03-25', emp_id: 'INS027', student_id: 'STU242', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 3, student_nationality: 'Sudanese',    student_gender: 'M', notes: 'Average' },
    { lesson_id: 'L182',  date: '2024-01-02', emp_id: 'INS001', student_id: 'STU243', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Senior instructor excellence' },
    { lesson_id: 'L183',  date: '2024-01-03', emp_id: 'INS001', student_id: 'STU244', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Masterful' },
    { lesson_id: 'L184',  date: '2024-01-04', emp_id: 'INS002', student_id: 'STU245', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: "Women's section head is amazing" },
    { lesson_id: 'L185',  date: '2024-01-05', emp_id: 'INS002', student_id: 'STU246', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'Perfect for female students' },
    { lesson_id: 'L186',  date: '2024-02-25', emp_id: 'INS003', student_id: 'STU247', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Indian',      student_gender: 'M', notes: 'Excellent as always' },
    { lesson_id: 'L187',  date: '2024-02-26', emp_id: 'INS003', student_id: 'STU248', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Pakistani',   student_gender: 'M', notes: 'Best instructor' },
    { lesson_id: 'L188',  date: '2024-02-27', emp_id: 'INS003', student_id: 'STU249', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Bangladeshi', student_gender: 'M', notes: 'Highly recommended' },
    { lesson_id: 'L189',  date: '2024-02-28', emp_id: 'INS005', student_id: 'STU250', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Kenyan',      student_gender: 'M', notes: 'Very good' },
    { lesson_id: 'L190',  date: '2024-02-29', emp_id: 'INS005', student_id: 'STU251', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 4, student_nationality: 'Ugandan',     student_gender: 'M', notes: 'Good' },
    { lesson_id: 'L191',  date: '2024-03-01', emp_id: 'INS005', student_id: 'STU252', vehicle_type: 'Traditional', duration: 60, passed: 'No',  satisfaction: 3, student_nationality: 'Nigerian',    student_gender: 'M', notes: 'Rushed again' },
    { lesson_id: 'L192',  date: '2024-03-02', emp_id: 'INS005', student_id: 'STU253', vehicle_type: 'Traditional', duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Ghanaian',    student_gender: 'M', notes: 'Excellent' },
    { lesson_id: 'L193',  date: '2024-01-21', emp_id: 'INS011', student_id: 'STU254', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'The future of driving schools' },
    { lesson_id: 'L194',  date: '2024-01-22', emp_id: 'INS011', student_id: 'STU255', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Amazing technology' },
    { lesson_id: 'L195',  date: '2024-01-23', emp_id: 'INS011', student_id: 'STU256', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Emirati',     student_gender: 'F', notes: 'So glad I chose this' },
    { lesson_id: 'L196',  date: '2024-01-24', emp_id: 'INS011', student_id: 'STU257', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Saudi',       student_gender: 'F', notes: 'Learned so fast' },
    { lesson_id: 'L197',  date: '2024-01-25', emp_id: 'INS011', student_id: 'STU258', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Worth every riyal' },
    { lesson_id: 'L198',  date: '2024-01-26', emp_id: 'INS011', student_id: 'STU259', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Kuwaiti',     student_gender: 'F', notes: 'Incredible experience' },
    { lesson_id: 'L199',  date: '2024-01-27', emp_id: 'INS011', student_id: 'STU260', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'F', notes: 'The sensors are amazing' },
    { lesson_id: 'L200',  date: '2024-01-28', emp_id: 'INS011', student_id: 'STU261', vehicle_type: 'Autonomous',  duration: 60, passed: 'Yes', satisfaction: 5, student_nationality: 'Qatari',      student_gender: 'M', notes: 'Passed first time easily' }
  ],

  dataset_3_student_feedback: [
    { feedback_id: 'F001', date: '2024-02-15', emp_id: 'INS010', student_id: 'STU060', rating: 2, comment_text: 'The instructor made comments about my appearance. I felt very uncomfortable being alone with him.', flagged_for_review: 'YES' },
    { feedback_id: 'F002', date: '2024-02-15', emp_id: 'INS010', student_id: 'STU061', rating: 1, comment_text: "He asked for my phone number and said we could 'practice privately'. This is unacceptable.", flagged_for_review: 'YES' },
    { feedback_id: 'F003', date: '2024-02-16', emp_id: 'INS010', student_id: 'STU062', rating: 2, comment_text: 'Used very bad language when I made a mistake. Swore at me. Not what I expect from Alkhebra.', flagged_for_review: 'YES' },
    { feedback_id: 'F004', date: '2024-02-17', emp_id: 'INS010', student_id: 'STU064', rating: 1, comment_text: 'I specifically requested a female instructor but was given him. He made me so uncomfortable I want to cancel my remaining lessons.', flagged_for_review: 'YES' },
    { feedback_id: 'F005', date: '2024-03-01', emp_id: 'INS004', student_id: 'STU066', rating: 2, comment_text: "He hinted that if I wanted to pass, I needed to 'appreciate' him. Very disappointing.", flagged_for_review: 'YES' },
    { feedback_id: 'F006', date: '2024-03-02', emp_id: 'INS004', student_id: 'STU067', rating: 2, comment_text: "Said there's an 'express pass' if I pay extra. This feels like corruption.", flagged_for_review: 'YES' },
    { feedback_id: 'F007', date: '2024-03-02', emp_id: 'INS004', student_id: 'STU068', rating: 1, comment_text: 'Openly asked for 2000 QAR to guarantee my pass. I am reporting this.', flagged_for_review: 'YES' },
    { feedback_id: 'F008', date: '2024-03-03', emp_id: 'INS004', student_id: 'STU069', rating: 2, comment_text: 'Corrupt instructor. Wanted money to pass me. This is against Islamic values.', flagged_for_review: 'YES' }
  ],

  dataset_4_ethical_risk_flags: [
    {
      emp_id: 'INS010',
      name: 'David Omondi',
      risk_score_0_100: 94,
      risk_category: 'Inappropriate Conduct',
      top_risk_factors: '4 complaints from female students, asked for phone number, foul language',
      top_risk_factors_ar: '٤ شكاوى من طالبات، طلب أرقام هواتف، استخدام ألفاظ بذيئة',
      pattern_detected: 'Targeting female students, pattern of inappropriate comments',
      recommended_action: 'IMMEDIATE SUSPENSION PENDING INVESTIGATION',
      recommended_action_ar: 'إيقاف فوري ريثما يُستكمل التحقيق'
    },
    {
      emp_id: 'INS004',
      name: 'Samir Khalil',
      risk_score_0_100: 97,
      risk_category: 'Bribery/Corruption',
      top_risk_factors: '5 separate bribe allegations, all from male students, pattern of "express pass" offers',
      top_risk_factors_ar: '٥ اتهامات رشوة منفصلة، جميعها من طلاب ذكور، نمط متكرر لعروض "التمرير السريع"',
      pattern_detected: 'Systematic bribery scheme, preying on desperate students',
      recommended_action: 'IMMEDIATE TERMINATION & LEGAL CONSULTATION',
      recommended_action_ar: 'إنهاء خدمة فوري والتشاور القانوني'
    },
    {
      emp_id: 'INS005',
      name: 'Yusuf Abdi',
      risk_score_0_100: 12,
      risk_category: 'Low Risk',
      top_risk_factors: 'One complaint about rushing, otherwise excellent feedback',
      pattern_detected: 'Isolated incident, possibly due to workload',
      recommended_action: 'Coaching on pacing, monitor workload'
    },
    {
      emp_id: 'INS003',
      name: 'Mohammed Iqbal',
      risk_score_0_100: 8,
      risk_category: 'Low Risk',
      top_risk_factors: 'All positive feedback, 100% pass rate',
      pattern_detected: 'High performer, no concerns',
      recommended_action: 'None - high performer'
    },
    {
      emp_id: 'INS011',
      name: 'Rashid Al-Kuwari',
      risk_score_0_100: 2,
      risk_category: 'Minimal Risk',
      top_risk_factors: 'All perfect feedback, autonomous vehicle specialist',
      pattern_detected: 'Innovation champion',
      recommended_action: 'Feature in marketing'
    },
    {
      emp_id: 'INS012',
      name: 'Nadia Cherif',
      risk_score_0_100: 3,
      risk_category: 'Minimal Risk',
      top_risk_factors: "All perfect feedback from female students",
      pattern_detected: "Women's section star performer",
      recommended_action: 'Retention priority'
    }
  ],

  dataset_5_inst_lifetime_value: [
    { emp_id: 'INS001', name: 'Ahmed Al-Mansoori', status: 'Active', tenure_months: 36, recruitment_plus_licensing_cost: 2000, total_salary_paid: 450000, revenue_generated: 720000, net_value: 268000, breakeven_month: 'Month 4', current_value: 'Profitable' },
    { emp_id: 'INS002', name: 'Fatima Al-Hajri', status: 'Active', tenure_months: 34, recruitment_plus_licensing_cost: 2000, total_salary_paid: 425000, revenue_generated: 680000, net_value: 253000, breakeven_month: 'Month 4', current_value: 'Profitable' },
    { emp_id: 'INS003', name: 'Mohammed Iqbal', status: 'Active', tenure_months: 13, recruitment_plus_licensing_cost: 58000, total_salary_paid: 97500, revenue_generated: 156000, net_value: 500, breakeven_month: 'Month 13', current_value: 'JUST BREAKEVEN' },
    { emp_id: 'INS004', name: 'Samir Khalil', status: 'Terminated', tenure_months: 11, recruitment_plus_licensing_cost: 57500, total_salary_paid: 77000, revenue_generated: 88000, net_value: -46500, breakeven_month: 'Month 14', current_value: 'LOSS: 46,500 QAR' },
    { emp_id: 'INS005', name: 'Yusuf Abdi', status: 'Active', tenure_months: 12, recruitment_plus_licensing_cost: 59000, total_salary_paid: 86400, revenue_generated: 115200, net_value: -30200, breakeven_month: 'Month 16', current_value: 'STILL IN LOSS' },
    { emp_id: 'INS006', name: 'Hassan Razak', status: 'Terminated', tenure_months: 11, recruitment_plus_licensing_cost: 57000, total_salary_paid: 74800, revenue_generated: 66000, net_value: -65800, breakeven_month: 'Month 15', current_value: 'LOSS: 65,800 QAR' },
    { emp_id: 'INS007', name: 'Aisha Syed', status: 'Active', tenure_months: 11, recruitment_plus_licensing_cost: 58500, total_salary_paid: 82500, revenue_generated: 110000, net_value: -31000, breakeven_month: 'Month 15', current_value: 'STILL IN LOSS' },
    { emp_id: 'INS008', name: 'Karim Mostafa', status: 'Active', tenure_months: 10, recruitment_plus_licensing_cost: 56500, total_salary_paid: 78000, revenue_generated: 104000, net_value: -30500, breakeven_month: 'Month 14', current_value: 'STILL IN LOSS' },
    { emp_id: 'INS009', name: 'Layla Hassan', status: 'Active', tenure_months: 9, recruitment_plus_licensing_cost: 56000, total_salary_paid: 72000, revenue_generated: 96000, net_value: -32000, breakeven_month: 'Month 13', current_value: 'STILL IN LOSS' },
    { emp_id: 'INS010', name: 'David Omondi', status: 'Terminated', tenure_months: 9, recruitment_plus_licensing_cost: 59000, total_salary_paid: 64800, revenue_generated: 54000, net_value: -69800, breakeven_month: 'Month 15', current_value: 'LOSS: 69,800 QAR' },
    { emp_id: 'INS011', name: 'Rashid Al-Kuwari', status: 'Active', tenure_months: 16, recruitment_plus_licensing_cost: 2000, total_salary_paid: 208000, revenue_generated: 332800, net_value: 122800, breakeven_month: 'Month 4', current_value: 'Profitable' },
    { emp_id: 'INS012', name: 'Nadia Cherif', status: 'Active', tenure_months: 7, recruitment_plus_licensing_cost: 57000, total_salary_paid: 53200, revenue_generated: 71000, net_value: -39200, breakeven_month: 'Month 14', current_value: 'STILL IN LOSS' },
    { emp_id: 'INS013', name: 'Tariq Mahmood', status: 'Active', tenure_months: 6, recruitment_plus_licensing_cost: 58000, total_salary_paid: 45000, revenue_generated: 60000, net_value: -43000, breakeven_month: 'Month 15', current_value: 'STILL IN LOSS' },
    { emp_id: 'INS014', name: 'Priya Krishnamurthy', status: 'Terminated', tenure_months: 6, recruitment_plus_licensing_cost: 58500, total_salary_paid: 44400, revenue_generated: 48000, net_value: -54900, breakeven_month: 'Month 15', current_value: 'LOSS: 54,900 QAR' },
    { emp_id: 'INS015', name: 'Abdullah Al-Marri', status: 'Active', tenure_months: 20, recruitment_plus_licensing_cost: 2000, total_salary_paid: 270000, revenue_generated: 432000, net_value: 160000, breakeven_month: 'Month 4', current_value: 'Profitable' }
  ],

  dataset_6_old_cars_vs_new: [
    { metric: 'Average Lessons to Pass', metric_ar: 'متوسط الدروس للنجاح', traditional_vehicle: '18 lessons', traditional_ar: '١٨ درساً', autonomous_vehicle: '12 lessons', autonomous_ar: '١٢ درساً', difference: '-6 lessons (-33%)', diff_ar: '-٦ دروس (-٣٣٪)', annualized_impact: 'Students progress faster' },
    { metric: 'First-Time Pass Rate', metric_ar: 'معدل النجاح من المحاولة الأولى', traditional_vehicle: '0.68', traditional_ar: '٠٫٦٨', autonomous_vehicle: '0.94', autonomous_ar: '٠٫٩٤', difference: '0.26', diff_ar: '+٠٫٢٦', annualized_impact: 'Higher success rate' },
    { metric: 'Student Satisfaction', metric_ar: 'رضا الطلاب', traditional_vehicle: '4.2/5', traditional_ar: '٤٫٢/٥', autonomous_vehicle: '4.9/5', autonomous_ar: '٤٫٩/٥', difference: '0.7', diff_ar: '+٠٫٧', annualized_impact: 'Better reviews' },
    { metric: 'Instructor Hours Required', metric_ar: 'ساعات المدرب المطلوبة', traditional_vehicle: '18 hours', traditional_ar: '١٨ ساعة', autonomous_vehicle: '8 hours', autonomous_ar: '٨ ساعات', difference: '-10 hours (-56%)', diff_ar: '-١٠ ساعات (-٥٦٪)', annualized_impact: 'Massive cost savings' },
    { metric: 'Instructor Cost per Student', metric_ar: 'تكلفة المدرب لكل طالب', traditional_vehicle: '1,350 QAR', traditional_ar: '١٣٥٠ ريال', autonomous_vehicle: '600 QAR', autonomous_ar: '٦٠٠ ريال', difference: '-750 QAR', diff_ar: '-٧٥٠ ريال', annualized_impact: '75,000 QAR savings per 100 students' },
    { metric: 'Vehicle Utilization', metric_ar: 'معدل استخدام المركبة', traditional_vehicle: '0.7', traditional_ar: '٠٫٧', autonomous_vehicle: '0.85', autonomous_ar: '٠٫٨٥', difference: '0.15', diff_ar: '+٠٫١٥', annualized_impact: 'More lessons possible' },
    { metric: 'Female Student Preference', metric_ar: 'تفضيل الطالبات', traditional_vehicle: '65% request female', traditional_ar: '٦٥٪ يطلبن مدربة', autonomous_vehicle: '92% comfortable', autonomous_ar: '٩٢٪ مرتاحات', difference: '0.27', diff_ar: '+٠٫٢٧', annualized_impact: 'Cultural fit advantage' }
  ],

  dataset_7_financial_loss: [
    {
      category: 'Instructors who left before breakeven',
      count: '4 (INS004, INS006, INS010, INS014)',
      total_loss_qar: '237,000 QAR',
      details: '50k licensing + recruitment + salary paid with no return'
    },
    {
      category: 'Instructors still in loss period',
      count: '5 (INS005, INS007, INS008, INS009, INS012, INS013)',
      total_loss_qar: '206,100 QAR',
      details: 'Currently underwater, at risk of leaving'
    },
    {
      category: 'Total Current Financial Bleed',
      count: '9 instructors',
      total_loss_qar: '443,100 QAR',
      details: 'Almost HALF A MILLION invested with no return yet'
    },
    {
      category: 'Ethical violation settlements (estimated)',
      count: '2 major cases',
      total_loss_qar: '150,000 QAR',
      details: 'Legal fees, settlements, student refunds'
    },
    {
      category: 'GRAND TOTAL LOSS (Last 12 Months)',
      count: null,
      total_loss_qar: '593,100 QAR',
      details: 'Enough to license 12 NEW instructors'
    }
  ]
};

window.ALKHEBRA_DATA = {
  kpis: {
    annualBleedQar: 593100,
    activeEthicsAlerts: 2,
    aiCarFasterPassPercent: 33
  },
  financial: {
    terminated: DB.dataset_5_inst_lifetime_value.filter(r => r.status === 'Terminated').map(r => ({
      id: r.emp_id,
      name: r.name,
      months: r.tenure_months,
      breakeven: parseInt((r.breakeven_month || '').replace(/\D/g, ''), 10) || 0,
      loss: Math.abs(r.net_value),
      nationality: (DB.dataset_1_instructor_master.find(i => i.emp_id === r.emp_id) || {}).nationality || ''
    })),
    atRisk: DB.dataset_5_inst_lifetime_value.filter(r => r.current_value && r.current_value.indexOf('STILL IN LOSS') >= 0).map(r => ({
      id: r.emp_id,
      name: r.name,
      months: r.tenure_months,
      breakeven: parseInt((r.breakeven_month || '').replace(/\D/g, ''), 10) || 0,
      loss: Math.abs(r.net_value)
    })),
    totalLoss: 237000,
    atRiskTotal: 206100,
    grandTotalBleed: 593100
  },
  ethics: {
    highRisk: DB.dataset_4_ethical_risk_flags.filter(r => r.risk_score_0_100 >= 90).map(r => ({
      id: r.emp_id,
      name: r.name,
      score: r.risk_score_0_100,
      category: r.risk_category.replace('/', ' / '),
      complaints: r.emp_id === 'INS010' ? 4 : 5,
      gender: (DB.dataset_1_instructor_master.find(i => i.emp_id === r.emp_id) || {}).gender || 'M',
      factors: r.top_risk_factors.split(',').map(s => s.trim()),
      factors_ar: r.top_risk_factors_ar ? r.top_risk_factors_ar.split('،').map(s => s.trim()) : [],
      keywords: [],
      action: r.recommended_action,
      action_ar: r.recommended_action_ar || ''
    }))
  },
  innovation: {
    comparison: DB.dataset_6_old_cars_vs_new.map(row => ({
      metric: row.metric,
      metric_ar: row.metric_ar || '',
      traditional: row.traditional_vehicle,
      traditional_ar: row.traditional_ar || '',
      autonomous: row.autonomous_vehicle,
      autonomous_ar: row.autonomous_ar || '',
      diff: row.difference,
      diff_ar: row.diff_ar || ''
    })),
    annualSavings: 900000,
    roiMonths: 8,
    costPerStudent: { trad: 1350, auto: 600 }
  },
  questions: {
    financialBleed: {
      question: 'Show me which instructors are costing us money by leaving too early.',
      summaryKpi: 'Total current financial bleed: 593,100 QAR (last 12 months)'
    },
    ethicalRisk: {
      question: 'Are there any instructors showing signs of behavior that violates our Islamic values?',
      activeRedAlerts: 2
    },
    innovationRoi: {
      question: 'Is our self-driving teaching car actually delivering value?',
      monthlySavingPer100StudentsQar: 75000
    }
  }
};